apiVersion: v1
entries:
  geopulse:
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2025-10-30T17:25:10.77971+02:00"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: e0c9971a43d5ee8d3527927e8d00fd701ce93054c1b7287b9ae0f7380b95cc97
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2025-10-30T17:25:10.776391+02:00"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: fba5326acfcf8362f4d929cfcd7e4828e506a611b6248345f39a22e9ecb241f0
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.2.tgz
    version: 1.1.2
generated: "2025-10-30T17:25:10.774865+02:00"
